[package]
name = "brainrust"
version = "0.1.0"
authors = ["Angelo Rendina <angelo.rendina91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
